version: '3.8'
services:
  inventory-service:
    build:
      context: ./inventory
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=aluglass

  sales-order-service:
    build:
      context: ./sales-order
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=aluglass

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: aluglass
    ports:
      - "3306:3306"